### ISSUE TITLE
Licensing permissions

### ISSUE THREAD

**Issue by jbrry** [coli-saar/am-parser#84]
Hi there,

I found certain parts of your software to be very helpful. In particular, for encoding the different features: https://github.com/coli-saar/am-parser/blob/5ffb66909737b9a625dbe378d4e246fbbd3337a6/graph_dependency_parser/graph_dependency_parser.py#L219

Secondly, I experimented with the Kiperwasser and Goldberg model for the 2020 IWPT shared task using the code here: https://github.com/coli-saar/am-parser/blob/5ffb66909737b9a625dbe378d4e246fbbd3337a6/graph_dependency_parser/components/edge_models/KG.py#L104

We ultimately didn't use the KG model as we had just used it for a preliminary experiment to compare VRAM usage and we didn't carry out a proper evaluation before the deadline so we unfortunately did not get to mention this model in our system submission but the KG code for scoring edges/deprels is still in our repository, where we will hopefully get to carry out some further analysis with more time.

As we want to release our code, we are wondering what is the best way to do this is? At the moment, I have links to your original files but I do not see a license so I am not sure under what circumstances the code can be used/redistributed. Alternatively, I could remove the models which use KG scoring until it is used in a subsequent paper where I can properly cite the original work.

Many thanks

**Comment by namednil** [comment]
Hi James,

thanks for reaching out! We discussed this and decided to make the code available under the Apache License, so feel free to include our code with a short notice into your codebase.

Hope the shared task went well!

**Comment by jbrry** [comment]
Hi Matthias,

Thank you for that, will do!
