### ISSUE TITLE
'nan loss encountered' on train.py

### ISSUE THREAD

**Issue by smlukin** [coli-saar/am-parser#94]
Hello, I have been trying to retrain the parser on a new dataset, but am encountering a 'NaN loss' error. 

This triggers from `train.py` on line 217: 
```
metrics = trainer.train(experiment, model_path = serialization_dir)
```

And is traced to `graph_dependency_parser/train/amtrainer.py ` on line 347-348:
```
if torch.isnan(loss):
  raise ValueError("nan loss encountered")
```

I noticed the documentation describes a `grad_clipping` parameter to help with NaNs, but I have not found the optimal value. 

Here is my clipped standard out from running `train.py`
```
2021-09-21 17:44:00,759 - INFO - graph_dependency_parser.train.amtrainer - Peak CPU memory usage MB: 3766.564
2021-09-21 17:44:00,934 - INFO - graph_dependency_parser.train.amtrainer - Training
  0%|          | 0/15 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    metrics = trainer.train(experiment, model_path = serialization_dir)
  File "graph_dependency_parser/train/amtrainer.py", line 503, in train
    train_metrics = self._train_epoch(epoch)
  File "graph_dependency_parser/train/amtrainer.py", line 348, in _train_epoch
    raise ValueError("nan loss encountered")
ValueError: nan loss encountered
```

I have encountered this error on an Ubuntu 16.04 and 18.04 in a conda and docker environment. (I have also tried on a Mac using conda and did not encounter the error, strangely.) Do you have an idea what might be causing the error in the first place, and what I can try next?

Thank you

**Comment by jgroschwitz** [comment]
Hi Stephanie, thanks for trying our parser! Unfortunately I don't have a solution off the top of my hat, haven't seen this before. What versions of AllenNLP and PyTorch are you using? We have tested the code with AllenNLP 0.8.4 and Pytorch 1.1; other versions can lead to errors.

If that's not the issue, @namednil could you help with the gradient clipping part? That's outside my area of expertise.

**Comment by smlukin** [comment]
Thank you for following.up. Our team is trying to debug the issue as well, and can share the following: 
1. We have pytorch 1.1.0 and allennlp 0.8.4 installed.
2. We have gotten NaN values from two functions: `loss` in `DMLabelLoss` and `label_scores` in `KGEdges`.
3. We added `torch.autograd.set_detect_anomaly(True)`` to detect where the NaNs were coming from and got a message:
```
RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output.
```
4. This only happens when we try to train the parser on Ubuntu; we have had success using the same code on a Mac

**Comment by namednil** [comment]
Hi! I don't know what might be going on, so I'm afraid my questions are a bit exploratory:

1. Does this happen immediately or after training for a while? 
2. Related to that: what are the forward values before this happens (NaN or -inf or +inf, for example?)
3. Does this happen both on CPU and GPU?
4. Which function causes the NaN in `label_scores` in `KGEdges`? There is no softmax there.

**Comment by smlukin** [comment]
1. This error occurs immediately after training starts.
2. For the issue in computing `loss()` in `losses/DM.py`, the function `masked_log_softmax()` produces a tensor with NaNs. The input to this function (`edge_label_logits`) is a tensor with non-NaNs and with a max value of 1.1679.
3. It happens on both GPU and CPU.
4. For the second issue of NaNs inside `label_scores`, we're still trying to figure that out.

**Comment by namednil** [comment]
It sounds like something unusual is happening within `masked_log_softmax`. Just to make sure I understand the situation,  `masked_log_softmax` already produces NaNs on the forward pass, right (the anomaly detection seems to complain about the backward pass)? Judging from its [source code](https://github.com/allenai/allennlp/blob/030ef755aeeee7d05d119dcfe367f81bb26aed53/allennlp/nn/util.py#L276), maybe your machine treats `(mask + 1e-45).log()` as `-inf` for values of `mask` that are zero. In that case, adding a slightly bigger number might do the trick. Newer versions of AllenNLP use [`1e-13`](https://github.com/allenai/allennlp/blob/44155ac64f74d7f4f0da59bda849d7223ca34d1d/allennlp/nn/util.py#L2094).

**Comment by smlukin** [comment]
Yes, thank you! The problem is in the forward pass. It looks like for some reason, `(mask + 1e-45).log()` is being computed as `-inf` on our machine when `mask` is zero. Do you think you could create a patch to fix this?

**Comment by namednil** [comment]
I just pushed a new version where you can set `SMALL_FLOAT` to whatever you need but by default it still is `1e-45`: https://github.com/coli-saar/am-parser/blob/0f4533a87dd81837c0595475989bef33ac08e638/graph_dependency_parser/components/losses/DM.py#L29 

Hopefully this should fix the first problem.

**Comment by ablodge** [comment]
Thank you! This does fix both of our errors. It looks like the second NaN error was caused by the first.

Would you be able to set `SMALL_FLOAT` to `1e-13` by default in your code? For portability reasons, we would prefer not to need to modify your code on our side, but we can as a last resort.

**Comment by namednil** [comment]
That's great to hear! I just changed the default.

**Comment by alexanderkoller** [comment]
Thank you for taking care of this, Matthias!

**Comment by smlukin** [comment]
This is great, thank you very much!
